;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
off  dw 0000H
segl dw 2000H
off2 dw 02H
seg2 dw 2800H
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
START:
        MOV AX, DATA
	MOV DS, AX
	
	MOV AX,2000H
	MOV ES,AX
	
	; Write your code here
	LEA BX, off
	LEA DI,off2
	
ENDLESS:
        ; Write your code here
	
	call far ptr [BX]
	call far ptr [DI]
        JMP ENDLESS
CODE    ENDS
        END START