;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Perþembe Aralýk 15 2022
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
MYDAT    DB 20 DUP(0)
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
START PROC
        MOV AX, DATA
	MOV DS, AX
TEKRAR: 
      MOV DX,6AH 
      MOV AL,00H 
      OUT 6AH,AL
      IN AL,6AH
      CALL BOS 
      
      OUT 62H,AL
      JMP TEKRAR

ENDLESS: 

BOS PROC NEAR 
     PUSH CX 
     MOV CX,2000H 
L1: 
     LOOP L1
     POP CX 
     RET
BOS ENDP 

JMP ENDLESS
RET
START ENDP


	
CODE    ENDS
        END START