;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
DIZI    DB  5 DUP(?) 
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
		
START PROC FAR
MOV AX, DATA
MOV DS, AX

XOR DI,DI ; Sýfýrladný
XOR SI,SI ; 
MOV AL, 4DH  ; 8251 programladýðýmýz yer
OUT 82H, AL
MOV AL, 40H   ; 8251 resetlendi.
OUT 82H, AL 	
MOV AL, 4DH  ; 8251'den transmit read ready kontrol edilecek.
OUT 82H, AL	
MOV AL, 15H   ; kontrol word'e eriþim.
OUT 82H, AL

XOR AX, AX
MOV ES, AX
MOV AL, 78H ; Vector tablosuna seri veri okuma prosedür adresi verilir.
MOV AH, 4   ; INTR0
MUL AH 	   ; son 3 bite göre INTR0 belirlendi.
MOV BX, AX
LEA AX, SERI_VERI_OKU ;
MOV WORD PTR ES:[BX], AX
MOV AX, CS
MOV WORD PTR ES:[BX+2], AX

XOR AX, AX
MOV ES, AX
MOV AL, 79H ; Vector tablosuna veri göndermek için adres.INTR1
MOV AH, 4
MUL AH 
MOV BX, AX
LEA AX, SERI_VERI_YAZ
MOV WORD PTR ES:[BX], AX
MOV AX, CS
MOV WORD PTR ES:[BX+2], AX

MOV AL, 13H   ; ICW1 90H 'a yüklenir. 
OUT 90H, AL                        
MOV AL, 78H   ;ICW2 vector tabolusunu baþlatýr.
OUT 92H, AL
MOV AL, 03H   ;ICW4 için kullanýlýr. 
OUT 92H, AL
STI

ENDLESS:	


JMP ENDLESS
RET
START ENDP

SERI_VERI_YAZ PROC FAR
	CMP SI,5 ; SI 5 olmadýysa iþlemleri çalýþtýrma.
	JNE DIZI_HAZIR_DEGIL
	CMP DI,0 ; SI beþ oldu.Basmak için interruptý tekrar tetiklemek lazým. Ýnterrupt beklenir.
	JL  BITTI 
	MOV AL, DIZI[DI] ; AL artýrýlýr ve ekrana bastýrýlýr.
	INC AL
	OUT 80H , AL
	INC DI ; Dizinin sonraki indisine eriþilir.
	CMP DI,5 ;DI 5 olmuþsa SI,DI sýfýrlanýr.Deðilse daha deðer beklenir.
	JNZ DIZI_HAZIR_DEGIL
	XOR DI,DI
	XOR SI,SI
	DIZI_HAZIR_DEGIL:
	BITTI:
	IRET	
SERI_VERI_YAZ ENDP	

SERI_VERI_OKU  PROC FAR
	CMP SI,5 ; Eðer 5'e eþitse burayý çalýþtýrma 
	JZ ATLA
	IN  AL ,80H
	SHR AL, 1
	MOV DIZI[SI],AL
	INC SI 
	SUB AX, 48
	ATLA: ; 5 deðer geldiyse yazmaya baþlamalýyýz.; Yazma tetiklensin diye bir tane okuma interruptý göndermeliyiz.
	CMP SI,5 ; Sadece dizi 5 olduðunda boþluk basýlýr.
	JNZ ZIPLA
	MOV AL, 32 ; boþluk bastýrýlýr.
	OUT 80H,AL
	ZIPLA:
	IRET 
SERI_VERI_OKU  ENDP	
	
CODE    ENDS
        END START	